server.port: ${SERVICE_PORT:8092}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/accounting}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:secret}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
    consumer:
      auto-offset-reset: earliest
      group-id: wage-consumer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic: ${KAFKA_TOPIC:wage}

tax.rate: ${TAX_RATE:1.1}


management.endpoints.web.exposure.include: health, info, env