version: "3.8"
services:
  producer:
    image: cloudmore/producer-service:1.0-SNAPSHOT
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: wage
    ports:
      - 8091:8091

  consumer:
    image: cloudmore/consumer-service:1.0-SNAPSHOT
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: wage
      JDBC_DATABASE_URL: 'jdbc:mysql://db:3306/accounting'
      TAX_RATE: 1.1
    ports:
      - 8092:8092

  db:
    image: mysql:8
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: accounting
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8090:8080

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  mysql:
  kafka_data:
  zookeeper_data: